import numpy as np
import matplotlib.pyplot as plt
from plotWindow import plotWindow


np.set_printoptions(linewidth=150)
plt.rc("text", usetex=True)
plt.rc("font", family="serif")

x = np.fromfile("/tmp/robot_true_state.log", dtype=np.float64).reshape(-1, 9)
u = np.fromfile("/tmp/robot_lqr_command.log", dtype=np.float64).reshape(-1, 3)
# u = np.fromfile("/tmp/robot_pid_command.log", dtype=np.float64).reshape(-1, 3)

pw = plotWindow()

f = plt.figure()
plt.suptitle("Forward/Heading Velocity")
plt.subplot(2, 1, 1)
plt.grid(True)
plt.ylabel("Forward Velocity (m/s)")
plt.plot(x[:,0], x[:,1], color="b", linewidth=2.0, label="ForVel")
plt.legend()
plt.subplot(2, 1, 2)
plt.grid(True)
plt.ylabel("Heading Velocity (rad/s)")
plt.xlabel("Time (s)")
plt.plot(x[:,0], x[:,2], color="b", linewidth=2.0, label="HeadVel")
plt.legend()
pw.addPlot("Forward/Heading Velocity", f)

f = plt.figure()
plt.suptitle("Pendulum Angle and Rate")
plt.subplot(2, 1, 1)
plt.grid(True)
plt.ylabel("Angle (rad)")
plt.plot(x[:,0], x[:,3], color="b", linewidth=2.0, label="Angle")
plt.legend()
plt.subplot(2, 1, 2)
plt.grid(True)
plt.ylabel("Angular Rate (rad/s)")
plt.xlabel("Time (s)")
plt.plot(x[:,0], x[:,4], color="b", linewidth=2.0, label="Rate")
plt.legend()
pw.addPlot("Pendulum Angle and Rate", f)

f = plt.figure()
plt.suptitle("Motor Velocities")
plt.subplot(2, 1, 1)
plt.grid(True)
plt.ylabel("Left Motor Velocity (rad/s)")
plt.plot(x[:,0], x[:,5], color="b", linewidth=2.0, label="Left")
plt.legend()
plt.subplot(2, 1, 2)
plt.grid(True)
plt.ylabel("Right Motor Velocity (rad/s)")
plt.xlabel("Time (s)")
plt.plot(x[:,0], x[:,6], color="b", linewidth=2.0, label="Right")
plt.legend()
pw.addPlot("Motor Velocities", f)

f = plt.figure()
plt.suptitle("Motor Currents")
plt.subplot(2, 1, 1)
plt.grid(True)
plt.ylabel("Left Motor Current (amps)")
plt.plot(x[:,0], x[:,7], color="b", linewidth=2.0, label="Left")
plt.legend()
plt.subplot(2, 1, 2)
plt.grid(True)
plt.ylabel("Right Motor Current (amps)")
plt.xlabel("Time (s)")
plt.plot(x[:,0], x[:,8], color="b", linewidth=2.0, label="Right")
plt.legend()
pw.addPlot("Motor Currents", f)

f = plt.figure()
plt.suptitle("Voltage Commands")
plt.subplot(2, 1, 1)
plt.grid(True)
plt.ylabel("Left Motor Voltage (V)")
plt.plot(u[:,0], u[:,1], color="b", linewidth=2.0, label="Left")
plt.legend()
plt.subplot(2, 1, 2)
plt.grid(True)
plt.ylabel("Right Motor Voltage (V)")
plt.xlabel("Time (s)")
plt.plot(u[:,0], u[:,2], color="b", linewidth=2.0, label="Right")
plt.legend()
pw.addPlot("Voltage Commands", f)

pw.show()
